export const SET_PROCESSING = 'SET_PROCESSING'

export const SET_QUIZ_STARTED = 'SET_QUIZ_STARTED'
export const SET_CATEGORY_ID = 'SET_CATEGORY_ID'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
export const SET_DIFFICULTY_LEVEL = 'SET_DIFFICULTY_LEVEL'
export const SET_QUESTIONS_AMOUNT = 'SET_QUESTIONS_AMOUNT'
export const SET_MAX_QUESTIONS_AMOUNT = 'SET_MAX_QUESTIONS_AMOUNT'
export const INCREASE_CORRECT_ANSWERS_AMOUNT = 'INCREASE_CORRECT_ANSWERS_AMOUNT'
export const INCREASE_INCORRECT_ANSWERS_AMOUNT =
  'INCREASE_INCORRECT_ANSWERS_AMOUNT'
